ingress:
  className: "nginx-public"
  hosts:
    - host: agenticxp.huna2.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: agenticxp-ingress
      hosts:
        - agenticxp.huna2.com

mongodb:
  storage:
    requestedSize: 25Gi
  userDatabase:
    password: '${MONGODB_DATABASE_PASSWORD}'