admins: '${APP_ADMINS}'
env: prd
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
  className: "nginx-private"
  hosts:
    - host: agenticxp.internal.huna2.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: agenticxp-ingress-tls
      hosts:
        - agenticxp.internal.huna2.com

mongodb:
  storage:
    requestedSize: 25Gi
  settings:
    rootPassword: '${MONGODB_PASSWORD}'
  userDatabase:
    password: '${MONGODB_PASSWORD}'

dex:
  ingress:
    hosts:
      - host: idp.agenticxp.internal.huna2.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: dex-ingress-tls
        hosts:
          - idp.agenticxp.internal.huna2.com
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    className: "nginx-private"
  config:
    issuer: https://idp.agenticxp.internal.huna2.com
    connectors:
      - type: google
        id: google
        name: Google
        config:
          clientID: ${GOOGLE_CLIENT_ID}
          clientSecret: ${GOOGLE_CLIENT_SECRET}
          redirectURI: https://idp.agenticxp.internal.huna2.com/callback
    staticClients:
      - id: agenticxp
        public: true
        name: 'agenticxp'
        redirectURIs:
        - 'https://agenticxp.internal.huna2.com'