apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agenticxp.fullname" . }}
  labels:
    {{- include "agenticxp.labels" . | nindent 4 }}
data:
  MONGODB_USER: {{ .Values.mongodb.userDatabase.user }}
  MONGODB_DATABASE: {{ .Values.mongodb.userDatabase.name }}
  MONGODB_HOST: "{{ include "agenticxp.fullname" . }}-mongodb"
  MONGODB_PORT: "27015"
  OIDC_CLIENT_ID: {{ (index .Values.dex.config.staticClients 0).id }}
  OIDC_ISSUER: {{ .Values.dex.config.issuer }}
  OIDC_ISSUER_INTERNAL: "http://{{ include "agenticxp.fullname" . }}-dex:5556"
  VITE_OIDC_CLIENT_ID: {{ (index .Values.dex.config.staticClients 0).id }}
  VITE_OIDC_ISSUER: {{ .Values.dex.config.issuer }}