apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agenticxp.fullname" . }}
  labels:
    {{- include "agenticxp.labels" . | nindent 4 }}
data:
  MONGODB_USER: {{ .Values.mongodb.userDatabase.user }}
  MONGODB_DATABASE: {{ .Values.mongodb.userDatabase.name }}