apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agenticxp.fullname" . }}
  labels:
    {{- include "agenticxp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "agenticxp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "agenticxp.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agenticxp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "agenticxp.fullname" . }}
            - configMapRef:
                name: {{ include "agenticxp.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: opa
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "openpolicyagent/opa:{{ .Values.opa.image.tag }}"
          imagePullPolicy: {{ .Values.opa.image.pullPolicy }}
          args:
            - 'run'
            - '--server'
            - '--config-file=/config/opa-config.yaml'
            - '--addr=0.0.0.0:8081'
            - '--diagnostic-addr=0.0.0.0:8082'
            - '/policy'
          ports:
            - name: opahttp
              containerPort: 8081
              protocol: TCP
            - name: opadiag
              containerPort: 8082
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: opadiag
          readinessProbe:
            httpGet:
              path: /health
              port: opadiag
          volumeMounts:
            - name: opa-config
              mountPath: /config
              readOnly: true
            - name: opa-policy
              mountPath: /policy
              readOnly: true
          resources:
            {{- toYaml .Values.opa.resources | nindent 12 }}

      volumes:
        - name: opa-config
          configMap:
            name: {{ include "agenticxp.fullname" . }}-opa-config
        - name: opa-policy
          configMap:
            name: {{ include "agenticxp.fullname" . }}-opa-policy
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
