apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agenticxp.fullname" . }}-opa-data
  labels:
    {{- include "agenticxp.labels" . | nindent 4 }}
data:
  data.json: |
    {
        "idp": {
            "issuerInternalUrl": "http://{{ include "agenticxp.fullname" . }}-dex:5556"
        },
        "adminEmails": ["root@root.root"{{- $admins := split "," .Values.admins -}}{{- range $i, $e := $admins }}{{- if $i }}, {{ end }}"{{ $e }}"{{- end }}]
    }