apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agenticxp.fullname" . }}-opa-config
  labels:
    {{- include "agenticxp.labels" . | nindent 4 }}
data:
  opa-config.yaml: |
    decision_logs:
      console: true