apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agenticxp.fullname" . }}-opa-policy
  labels:
    {{- include "agenticxp.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "policies/rego/*.rego").AsConfig | indent 2 }}