apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agenticxp.fullname" . }}
  labels:
    {{- include "agenticxp.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_PASSWORD: {{ .Values.mongodb.userDatabase.password | b64enc }}