name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  VERSION: '1.0.0'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-main-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-main-
            ${{ runner.os }}-buildx-

      - name: Login to GHCR (only on main)
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build & Conditional Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
          tags: ghcr.io/alinflorin/agenticxp:${{ env.VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move new cache into place
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract and bump version
        id: version
        run: |
          sed -i "s/^version:.*/version: $VERSION/" chart/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"$VERSION\"/" chart/Chart.yaml

      - name: Log in to GHCR for Helm
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Package Helm chart
        working-directory: chart
        run: |
          helm package .

      - name: Push Helm chart to GHCR
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        working-directory: chart
        run: |
          helm push agenticxp-*.tgz oci://ghcr.io/alinflorin/charts

  deploy:
    runs-on: ubuntu-latest
    needs: [docker, helm]
    strategy:
      matrix:
        environment: [stg, uat, prd]

    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    environment:
      name: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write Kubeconfig to file
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
          use-cache: 'true'

      - name: Log in to GHCR for Helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin


      - name: Deploy to ${{ matrix.environment }} environment with Helm
        run: |
          helm upgrade --kubeconfig ${{ github.workspace }}/kubeconfig.yaml --install --namespace agenticxp-${{ matrix.environment }} --create-namespace --values chart/values-${{ matrix.environment }}.yaml --version=${{ env.VERSION }} agenticxp oci://ghcr.io/alinflorin/charts/agenticxp
        
      - name: Remove kubeconfig file
        if: always()
        run: rm -rf ${{ github.workspace }}/kubeconfig.yaml || true